# name: Deploy
# on:
#   push:
#     branches:
#       - master
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Install Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           registry-url: https://registry.npmjs.com/

#       - uses: pnpm/action-setup@v3
#         name: Install pnpm
#         id: pnpm-install
#         with:
#           version: 9
#           run_install: false

#       - name: deploy
#         run: |
#           pnpm install
#           npm run build:mac
#           cd dist
#           touch README.md .nojekyll

#       - name: deploy
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           folder: dist
#           clean: true
